import type { Transaction } from '@/lib/types';

export const mockTransactions: Transaction[] = [
  {
    id: 'txn_1',
    date: '2024-07-20',
    description: 'فاتورة الكهرباء',
    amount: -350.0,
    type: 'دفع فاتورة',
    category: 'فواتير',
    status: 'Completed',
  },
  {
    id: 'txn_2',
    date: '2024-07-19',
    description: 'تحويل إلى أحمد كمال',
    amount: -500.0,
    type: 'تحويل',
    category: 'أخرى',
    status: 'Completed',
  },
  {
    id: 'txn_3',
    date: '2024-07-18',
    description: 'مشتريات من السوبر ماركت',
    amount: -450.5,
    type: 'شراء بالبطاقة',
    category: 'طعام',
    status: 'Completed',
  },
  {
    id: 'txn_4',
    date: '2024-07-17',
    description: 'شحن رصيد - فودافون',
    amount: -100.0,
    type: 'شحن رصيد',
    category: 'فواتير',
    status: 'Completed',
  },
  {
    id: 'txn_5',
    date: '2024-07-16',
    description: 'تم الاستلام من سارة علي',
    amount: 1000.0,
    type: 'دخل',
    category: 'دخل',
    status: 'Completed',
  },
  {
    id: 'txn_6',
    date: '2024-07-15',
    description: 'خدمة سيارات الأجرة',
    amount: -65.0,
    type: 'شراء بالبطاقة',
    category: 'مواصلات',
    status: 'Completed',
  },
  {
    id: 'txn_7',
    date: '2024-07-14',
    description: 'تسوق أونلاين - ملابس',
    amount: -850.0,
    type: 'شراء بالبطاقة',
    category: 'تسوق',
    status: 'Completed',
  },
  {
    id: 'txn_8',
    date: '2024-07-13',
    description: 'فاتورة الإنترنت',
    amount: -250.0,
    type: 'دفع فاتورة',
    category: 'فواتير',
    status: 'Completed',
  },
  {
    id: 'txn_9',
    date: '2024-07-12',
    description: 'عشاء مع الأصدقاء',
    amount: -280.0,
    type: 'شراء بالبطاقة',
    category: 'ترفيه',
    status: 'Pending',
  },
  {
    id: 'txn_10',
    date: '2024-07-11',
    description: 'فاتورة الغاز',
    amount: -120.0,
    type: 'دفع فاتورة',
    category: 'فواتير',
    status: 'Failed',
  },
];
