import type { Transaction } from '@/lib/types';

export const mockTransactions: Transaction[] = [
  {
    id: 'txn_1',
    date: '2024-07-20',
    description: 'Electricity Bill',
    amount: -350.0,
    type: 'Bill Payment',
    category: 'Bills',
    status: 'Completed',
  },
  {
    id: 'txn_2',
    date: '2024-07-19',
    description: 'Sent to Ahmed Kamal',
    amount: -500.0,
    type: 'Transfer',
    category: 'Other',
    status: 'Completed',
  },
  {
    id: 'txn_3',
    date: '2024-07-18',
    description: 'Groceries from Supermarket',
    amount: -450.5,
    type: 'Card Purchase',
    category: 'Food',
    status: 'Completed',
  },
  {
    id: 'txn_4',
    date: '2024-07-17',
    description: 'Mobile Recharge - Vodafone',
    amount: -100.0,
    type: 'Recharge',
    category: 'Bills',
    status: 'Completed',
  },
  {
    id: 'txn_5',
    date: '2024-07-16',
    description: 'Received from Sara Ali',
    amount: 1000.0,
    type: 'Income',
    category: 'Income',
    status: 'Completed',
  },
  {
    id: 'txn_6',
    date: '2024-07-15',
    description: 'Ride sharing service',
    amount: -65.0,
    type: 'Card Purchase',
    category: 'Transport',
    status: 'Completed',
  },
  {
    id: 'txn_7',
    date: '2024-07-14',
    description: 'Online Shopping - Clothes',
    amount: -850.0,
    type: 'Card Purchase',
    category: 'Shopping',
    status: 'Completed',
  },
  {
    id: 'txn_8',
    date: '2024-07-13',
    description: 'Internet Bill',
    amount: -250.0,
    type: 'Bill Payment',
    category: 'Bills',
    status: 'Completed',
  },
  {
    id: 'txn_9',
    date: '2024-07-12',
    description: 'Dinner with friends',
    amount: -280.0,
    type: 'Card Purchase',
    category: 'Entertainment',
    status: 'Pending',
  },
  {
    id: 'txn_10',
    date: '2024-07-11',
    description: 'Gas Bill',
    amount: -120.0,
    type: 'Bill Payment',
    category: 'Bills',
    status: 'Failed',
  },
];
